<?php
/**
 * Custom fields from ACF
 */

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_10-reasons',
		'title' => '10 Reasons',
		'fields' => array (
			array (
				'key' => 'field_52195e3542729',
				'label' => 'Reasons',
				'name' => '_eco_reason',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_52195e4c4272a',
						'label' => 'Image',
						'name' => '_eco_reason_image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_521969da4272b',
						'label' => 'Title',
						'name' => '_eco_reason_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_52196cc94272c',
						'label' => 'Description',
						'name' => '_eco_reason_desc',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'no',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-10reasons.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_affiliations',
		'title' => 'Affiliations',
		'fields' => array (
			array (
				'key' => 'field_5240eb862ff08',
				'label' => 'Affiliations',
				'name' => '_eco_affiliations',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5240eb972ff09',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5240eba82ff0a',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5240ebb52ff0b',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
					array (
						'key' => 'field_5240f5ed4f732',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'instructions' => '(optional)',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Affiliation',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-affiliations.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_awards-accolades',
		'title' => 'Awards & Accolades',
		'fields' => array (
			array (
				'key' => 'field_5240f875349c2',
				'label' => 'Awards & Accolades',
				'name' => '_eco_awards',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5240f63b7fb14',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5240f6457fb15',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5240f6557fb16',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Award',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-awards.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_cuzco-macchu-picchu-itineraries',
		'title' => 'Cuzco & Macchu Picchu: Itineraries',
		'fields' => array (
			array (
				'key' => 'field_5241b3e9f578b',
				'label' => '6 Night Premium First Class',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5241b402f578d',
				'label' => '6 night content',
				'name' => '_eco_6_night_content',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_5241b3f6f578c',
				'label' => '7 Night Luxury Collection',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5241b463f578e',
				'label' => '7 night content',
				'name' => '_eco_7_night_content',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-cuzco.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_downloads',
		'title' => 'Downloads',
		'fields' => array (
			array (
				'key' => 'field_524352f4d2d5b',
				'label' => 'Downloads',
				'name' => '_eco_downloads',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5240f63b7fb14',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5240f6457fb15',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5240f6557fb16',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
					array (
						'key' => 'field_5240f6767fb17',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'instructions' => '(optional)',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Download',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-downloads.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_guest-reviews',
		'title' => 'Guest Reviews',
		'fields' => array (
			array (
				'key' => 'field_52193cb78adef',
				'label' => 'Guest\'s Trip',
				'name' => '_eco_guests_trip',
				'type' => 'text',
				'instructions' => 'The yacht and date of the guest\'s trip',
				'default_value' => '',
				'placeholder' => 'e.g. M/Y Eric January 2013',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52194cfb35a8e',
				'label' => 'Show on Home Page',
				'name' => '_eco_show_on_home',
				'type' => 'true_false',
				'instructions' => 'Check this to show this review on the homepage (maximum of 2)',
				'message' => 'Show on Home page?',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'guest-review',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_guides-captains-crew',
		'title' => 'Guides, Captains & Crew',
		'fields' => array (
			array (
				'key' => 'field_522e2bff27639',
				'label' => 'Captains',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_522e2c9c2763a',
				'label' => 'Captains',
				'name' => '_eco_captains',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_522e2fba9ef6a',
						'label' => 'Name',
						'name' => '_eco_crew_name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_522e309650b8d',
						'label' => 'Title',
						'name' => '_eco_crew_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_522e2cff2763b',
						'label' => 'Headshot',
						'name' => '_eco_headshot',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_522e2d502763c',
						'label' => 'Description',
						'name' => '_eco_crew_description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'no',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Captain',
			),
			array (
				'key' => 'field_522e388520429',
				'label' => 'Guides',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_522e389b2042b',
				'label' => 'Guides',
				'name' => '_eco_guides',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_522e389b2042c',
						'label' => 'Name',
						'name' => '_eco_crew_name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_522e389b2042d',
						'label' => 'Title',
						'name' => '_eco_crew_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_522e389b2042e',
						'label' => 'Headshot',
						'name' => '_eco_headshot',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_522e389b2042f',
						'label' => 'Description',
						'name' => '_eco_crew_description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'no',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Guide',
			),
			array (
				'key' => 'field_522e388e2042a',
				'label' => 'Crew',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_522e3a0afc3f1',
				'label' => 'Crew Description and Image',
				'name' => '_eco_crew_description_and_image',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-guides.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_home-buttons',
		'title' => 'Home Buttons',
		'fields' => array (
			array (
				'key' => 'field_52194ffc9feed',
				'label' => 'Homepage Button 1 Title',
				'name' => '_eco_home_button_1_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Button 1 Title',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52194e8a2e15e',
				'label' => 'Homepage Button 1 Link',
				'name' => '_eco_home_button_1_link',
				'type' => 'page_link',
				'instructions' => 'Choose the page to link to for Button 1',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5219505ce2315',
				'label' => 'Homepage Button 2 Title',
				'name' => '_eco_home_button_2_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Button 2 Title',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52194f939feea',
				'label' => 'Homepage Button 2 Link',
				'name' => '_eco_home_button_2_link',
				'type' => 'page_link',
				'instructions' => 'Choose the page to link to for Button 2',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_52195079e2316',
				'label' => 'Homepage Button 3 Title',
				'name' => '_eco_home_button_3_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Button 3 Title',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52194fb89feeb',
				'label' => 'Homepage Button 3 Link',
				'name' => '_eco_home_button_3_link',
				'type' => 'page_link',
				'instructions' => 'Choose the page to link to for Button 3',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5219508de2317',
				'label' => 'Homepage Button 4 Title',
				'name' => '_eco_home_button_4_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Button 4 Title',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52194fcd9feec',
				'label' => 'Homepage Button 4 Link',
				'name' => '_eco_home_button_4_link',
				'type' => 'page_link',
				'instructions' => 'Choose the page to link to for Button 4',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '20',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_in-the-media',
		'title' => 'In the Media',
		'fields' => array (
			array (
				'key' => 'field_5218dff3acabd',
				'label' => 'Source URL',
				'name' => '_eco_source_url',
				'type' => 'text',
				'instructions' => 'Enter the original url to link to the press item.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5218e044acabe',
				'label' => 'File Upload',
				'name' => '_eco_file_upload',
				'type' => 'file',
				'instructions' => 'Use this to upload a PDF (optional)',
				'save_format' => 'object',
				'library' => 'all',
			),
			array (
				'key' => 'field_521938f832cbd',
				'label' => 'Show on Home Page',
				'name' => '_eco_show_on_home',
				'type' => 'true_false',
				'instructions' => 'Check this to show this item on the homepage (maximum of 6)',
				'message' => 'Show on Home page?',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'press',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_itineraries-itinerary-content',
		'title' => 'Itineraries: Itinerary Content',
		'fields' => array (
			array (
				'key' => 'field_521a5e9ec1c9b',
				'label' => 'Itinerary A',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_521a5fa40bf6f',
				'label' => 'Itinerary A Content',
				'name' => '_eco_itinerary_a_content',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_522c7ca1b0d84',
				'label' => 'Itinerary A Small Map',
				'name' => '_eco_itinerary_a_small_map',
				'type' => 'image',
				'instructions' => 'Select the itinerary map to be shown at the top (smaller). Set the title to be used as the title for the large map popup.',
				'required' => 1,
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_522c7d80b0d86',
				'label' => 'Itinerary A Large Map',
				'name' => '_eco_itinerary_a_large_map',
				'type' => 'image',
				'instructions' => 'Select the full-size map to be shown when the smaller map is clicked.',
				'required' => 1,
				'save_format' => 'id',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_522a593c6e26b',
				'label' => 'Itinerary A Slideshow',
				'name' => '_eco_itinerary_a_slideshow',
				'type' => 'gallery',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_521a5ed6c1c9d',
				'label' => 'Itinerary B',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_521a60040bf70',
				'label' => 'Itinerary B Content',
				'name' => '_eco_itinerary_b_content',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_522c7d57b0d85',
				'label' => 'Itinerary B Small Map',
				'name' => '_eco_itinerary_b_small_map',
				'type' => 'image',
				'instructions' => 'Select the itinerary map to be shown at the top (smaller). Set the title to be used as the title for the large map popup.',
				'required' => 1,
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_522c7dbab0d87',
				'label' => 'Itinerary B Large Map',
				'name' => '_eco_itinerary_b_large_map',
				'type' => 'image',
				'instructions' => 'Select the full-size map to be shown when the smaller map is clicked.',
				'required' => 1,
				'save_format' => 'id',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_521c0a6220455',
				'label' => 'Itinerary B Slideshow',
				'name' => '_eco_itinerary_b_slideshow',
				'type' => 'gallery',
				'instructions' => 'Add images to the slideshow for itinerary B',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_521bfc6ca8ceb',
				'label' => 'Stipulations & Additional Content',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_521bfc8aa8cec',
				'label' => 'Stipulations',
				'name' => '_eco_itinerary_stipulations',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-itineraries.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_our-cuisine-slideshow',
		'title' => 'Our Cuisine: Slideshow',
		'fields' => array (
			array (
				'key' => 'field_523dcb20262c3',
				'label' => 'Cuisine Gallery',
				'name' => '_eco_cuisine_gallery',
				'type' => 'gallery',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-cuisine.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_slides',
		'title' => 'Slides',
		'fields' => array (
			array (
				'key' => 'field_520e4a65948ca',
				'label' => 'Slide Caption',
				'name' => 'slide_caption',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'slide',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_suggested-reading',
		'title' => 'Suggested Reading',
		'fields' => array (
			array (
				'key' => 'field_522e7cc0f7ec5',
				'label' => 'Book Sections',
				'name' => '_eco_book_cats',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_522e8c101a85d',
						'label' => 'Title',
						'name' => '_eco_book_section_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_522e7d51f7eca',
						'label' => 'Books',
						'name' => '_eco_books',
						'type' => 'repeater',
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_522e8b4bf7ecb',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_522f2646802cc',
								'label' => 'Author',
								'name' => 'author',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_522e8b64f7ecc',
								'label' => 'Description',
								'name' => 'description',
								'type' => 'textarea',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'formatting' => 'html',
							),
							array (
								'key' => 'field_522e8b83f7ecd',
								'label' => 'Cover Image',
								'name' => 'cover_image',
								'type' => 'image',
								'instructions' => 'Get this from Amazon or Longitude (optional)',
								'column_width' => '',
								'save_format' => 'id',
								'preview_size' => 'media-thumb',
								'library' => 'all',
							),
							array (
								'key' => 'field_522e8b9df7ece',
								'label' => 'Link',
								'name' => 'link',
								'type' => 'text',
								'instructions' => 'purchase link for the book (optional)',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
						),
						'row_min' => 0,
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => 'Add Book',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Book Section',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-reading.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_team-members',
		'title' => 'Team Members',
		'fields' => array (
			array (
				'key' => 'field_5255bd0498f1e',
				'label' => 'Guayaquil',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5255bd7fe4e2e',
				'label' => 'Guayaquil Heading Text',
				'name' => '_eco_guayaquil_heading',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5255bd0499c22',
				'label' => 'Guayaquil',
				'name' => '_eco_team_guayaquil',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_522e2fba9ef6a',
						'label' => 'Name',
						'name' => '_eco_crew_name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_522e309650b8d',
						'label' => 'Title',
						'name' => '_eco_crew_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_522e2cff2763b',
						'label' => 'Headshot',
						'name' => '_eco_headshot',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_522e2d502763c',
						'label' => 'Description',
						'name' => '_eco_crew_description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Team Member',
			),
			array (
				'key' => 'field_5255bd049b16c',
				'label' => 'Quito',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5255bdbbe4e2f',
				'label' => 'Quito Heading Text',
				'name' => '_eco_quito_heading',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5255bd049bffb',
				'label' => 'Quito',
				'name' => '_eco_team_quito',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_522e389b2042c',
						'label' => 'Name',
						'name' => '_eco_crew_name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_522e389b2042d',
						'label' => 'Title',
						'name' => '_eco_crew_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_522e389b2042e',
						'label' => 'Headshot',
						'name' => '_eco_headshot',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_522e389b2042f',
						'label' => 'Description',
						'name' => '_eco_crew_description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Team Member',
			),
			array (
				'key' => 'field_5255bd049d36f',
				'label' => 'Galapagos',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5255bdd0e4e30',
				'label' => 'Galapagos Heading Text',
				'name' => '_eco_galapagos_heading',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5255be28e4e33',
				'label' => 'Galapgos',
				'name' => '_eco_team_galapagos',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5255be28e4e34',
						'label' => 'Name',
						'name' => '_eco_crew_name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5255be28e4e35',
						'label' => 'Title',
						'name' => '_eco_crew_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5255be28e4e36',
						'label' => 'Headshot',
						'name' => '_eco_headshot',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5255be28e4e37',
						'label' => 'Description',
						'name' => '_eco_crew_description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Team Member',
			),
			array (
				'key' => 'field_5255be05e4e31',
				'label' => 'Miami',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5255be18e4e32',
				'label' => 'Miami Heading Text',
				'name' => '_eco_miami_heading',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5255be36e4e38',
				'label' => 'Miami',
				'name' => '_eco_team_miami',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5255be36e4e39',
						'label' => 'Name',
						'name' => '_eco_crew_name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5255be36e4e3a',
						'label' => 'Title',
						'name' => '_eco_crew_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5255be36e4e3b',
						'label' => 'Headshot',
						'name' => '_eco_headshot',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5255be36e4e3c',
						'label' => 'Description',
						'name' => '_eco_crew_description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Team Member',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-team.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_trade-associations',
		'title' => 'Trade Associations',
		'fields' => array (
			array (
				'key' => 'field_5240f6217fb13',
				'label' => 'Trade Associations',
				'name' => '_eco_associations',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5240f63b7fb14',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5240f6457fb15',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5240f6557fb16',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
					array (
						'key' => 'field_5240f6767fb17',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'instructions' => '(optional)',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Trade Association',
			),
			array (
				'key' => 'field_525b4928e15ff',
				'label' => 'Trade Shows Heading',
				'name' => '_eco_trade_shows_heading',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_525b493fe1600',
				'label' => 'Trade Shows Content',
				'name' => '_eco_trade_shows_content',
				'type' => 'wysiwyg',
				'instructions' => '(Optional)',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_525b4957e1601',
				'label' => 'Trade Shows',
				'name' => '_eco_trade_shows',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_525b4957e1602',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_525b4957e1603',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_525b4957e1604',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
					array (
						'key' => 'field_525b4957e1605',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'instructions' => '(optional)',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Representation',
			),
			array (
				'key' => 'field_5252da1002fa0',
				'label' => 'Representation Heading',
				'name' => '_eco_representation_heading',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5252da2102fa1',
				'label' => 'Representation Content',
				'name' => '_eco_representation_content',
				'type' => 'wysiwyg',
				'instructions' => '(Optional)',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_5252da3a02fa2',
				'label' => 'Representations',
				'name' => '_eco_representations',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5252da3a02fa3',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5252da3a02fa4',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5252da3a02fa5',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
					array (
						'key' => 'field_5252da3a02fa6',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'instructions' => '(optional)',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Representation',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-associations.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_yachts',
		'title' => 'Yachts',
		'fields' => array (
			array (
				'key' => 'field_5240645b5bc00',
				'label' => 'Dolphin Deck',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_524077872a3ec',
				'label' => 'Dolphin Deck Slideshow',
				'name' => '_eco_dolphin_deck_images',
				'type' => 'repeater',
				'instructions' => 'Add photos for the Dolphin deck slideshow here (thumbnails will be automatically generated)',
				'sub_fields' => array (
					array (
						'key' => 'field_524077962a3ed',
						'label' => 'Deck Photo',
						'name' => 'deck_photo',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_524077a32a3ee',
						'label' => 'Deck Image Overlay',
						'name' => 'deck_image_overlay',
						'type' => 'radio',
						'column_width' => '',
						'choices' => array (
							'none' => 'None',
							'booby-deck-b-cabin' => 'Booby Deck B Cabin',
							'booby-deck-b-cabin-bathrooms' => 'Booby Deck B Cabin Bathrooms',
							'booby-deck-bar' => 'Booby Deck Bar',
							'booby-deck-conference-room' => 'Booby Deck Conference Room',
							'booby-deck-dining-room' => 'Booby Deck Dining Room',
							'dolphin-deck-bridge' => 'Dolphin Deck Bridge',
							'dolphin-deck-d1' => 'Dolphin Deck D1',
							'dolphin-deck-d2' => 'Dolphin Deck D2',
							'dolphin-deck-d3' => 'Dolphin Deck D3',
							'dolphin-deck-d4' => 'Dolphin Deck D4',
							'dolphin-deck-observation-deck' => 'Dolphin Deck Observation Deck',
							'dolphin-deck-observation-deck-2' => 'Dolphin Deck Observation Deck 2',
							'iguana-deck-cabin-17-18' => 'Iguana Deck Cabin 17 18',
							'iguana-deck-cabin-19-20' => 'Iguana Deck Cabin 19 20',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => 'none',
						'layout' => 'horizontal',
					),
					array (
						'key' => 'field_5240ac50797ea',
						'label' => 'Photo Title',
						'name' => 'photo_title',
						'type' => 'text',
						'instructions' => 'Displays the cabin title below the deck plan overlay (keep this short)',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Photo',
			),
			array (
				'key' => 'field_5240649c5bc01',
				'label' => 'Booby Deck',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5240bc27877d7',
				'label' => 'Booby Deck Slideshow',
				'name' => '_eco_booby_deck_images',
				'type' => 'repeater',
				'instructions' => 'Add photos for the Booby deck slideshow here (thumbnails will be automatically generated)',
				'sub_fields' => array (
					array (
						'key' => 'field_5240bc27877d8',
						'label' => 'Deck Photo',
						'name' => 'deck_photo',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5240bc27877d9',
						'label' => 'Deck Image Overlay',
						'name' => 'deck_image_overlay',
						'type' => 'radio',
						'column_width' => '',
						'choices' => array (
							'none' => 'None',
							'booby-deck-b-cabin' => 'Booby Deck B Cabin',
							'booby-deck-b-cabin-bathrooms' => 'Booby Deck B Cabin Bathrooms',
							'booby-deck-bar' => 'Booby Deck Bar',
							'booby-deck-conference-room' => 'Booby Deck Conference Room',
							'booby-deck-dining-room' => 'Booby Deck Dining Room',
							'dolphin-deck-bridge' => 'Dolphin Deck Bridge',
							'dolphin-deck-d1' => 'Dolphin Deck D1',
							'dolphin-deck-d2' => 'Dolphin Deck D2',
							'dolphin-deck-d3' => 'Dolphin Deck D3',
							'dolphin-deck-d4' => 'Dolphin Deck D4',
							'dolphin-deck-observation-deck' => 'Dolphin Deck Observation Deck',
							'dolphin-deck-observation-deck-2' => 'Dolphin Deck Observation Deck 2',
							'iguana-deck-cabin-17-18' => 'Iguana Deck Cabin 17 18',
							'iguana-deck-cabin-19-20' => 'Iguana Deck Cabin 19 20',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => 'none',
						'layout' => 'horizontal',
					),
					array (
						'key' => 'field_5240bc27877da',
						'label' => 'Photo Title',
						'name' => 'photo_title',
						'type' => 'text',
						'instructions' => 'Displays the cabin title below the deck plan overlay (keep this short)',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Photo',
			),
			array (
				'key' => 'field_524064a35bc02',
				'label' => 'Iguana Deck',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5240bc44877db',
				'label' => 'Iguana Deck Slideshow',
				'name' => '_eco_iguana_deck_images',
				'type' => 'repeater',
				'instructions' => 'Add photos for the Iguana deck slideshow here (thumbnails will be automatically generated)',
				'sub_fields' => array (
					array (
						'key' => 'field_5240bc44877dc',
						'label' => 'Deck Photo',
						'name' => 'deck_photo',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5240bc44877dd',
						'label' => 'Deck Image Overlay',
						'name' => 'deck_image_overlay',
						'type' => 'radio',
						'column_width' => '',
						'choices' => array (
							'none' => 'None',
							'booby-deck-b-cabin' => 'Booby Deck B Cabin',
							'booby-deck-b-cabin-bathrooms' => 'Booby Deck B Cabin Bathrooms',
							'booby-deck-bar' => 'Booby Deck Bar',
							'booby-deck-conference-room' => 'Booby Deck Conference Room',
							'booby-deck-dining-room' => 'Booby Deck Dining Room',
							'dolphin-deck-bridge' => 'Dolphin Deck Bridge',
							'dolphin-deck-d1' => 'Dolphin Deck D1',
							'dolphin-deck-d2' => 'Dolphin Deck D2',
							'dolphin-deck-d3' => 'Dolphin Deck D3',
							'dolphin-deck-d4' => 'Dolphin Deck D4',
							'dolphin-deck-observation-deck' => 'Dolphin Deck Observation Deck',
							'dolphin-deck-observation-deck-2' => 'Dolphin Deck Observation Deck 2',
							'iguana-deck-cabin-17-18' => 'Iguana Deck Cabin 17 18',
							'iguana-deck-cabin-19-20' => 'Iguana Deck Cabin 19 20',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => 'none',
						'layout' => 'horizontal',
					),
					array (
						'key' => 'field_5240bc44877de',
						'label' => 'Photo Title',
						'name' => 'photo_title',
						'type' => 'text',
						'instructions' => 'Displays the cabin title below the deck plan overlay (keep this short)',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Photo',
			),
			array (
				'key' => 'field_524064e85bc03',
				'label' => 'Cabins & Specs',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5240693325c51',
				'label' => 'Cabins content',
				'name' => '_eco_yachts_cabins_content',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-yachts.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_footer-content',
		'title' => 'Footer Content',
		'fields' => array (
			array (
				'key' => 'field_5241db8ad7c3f',
				'label' => 'Left Content',
				'name' => '_eco_footer_left_content',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_5241dbb3d7c40',
				'label' => 'Center Content',
				'name' => '_eco_footer_center_content',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_5241dbbfd7c41',
				'label' => 'Right Content',
				'name' => '_eco_footer_right_content',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'html',
			),
			array (
				'key' => 'field_5241dbd0d7c42',
				'label' => 'Footer Logos',
				'name' => '_eco_footer_logos',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_5241dbded7c43',
						'label' => 'Logo',
						'name' => 'image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5241dbf7d7c44',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => 0,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'front_page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_home-controls',
		'title' => 'Home Controls',
		'fields' => array (
			array (
				'key' => 'field_525c0a3f1746d',
				'label' => 'Number of In The Media Items to show',
				'name' => '_eco_media_items_count',
				'type' => 'number',
				'instructions' => 'Sets the maximum number of media items to show on the homepage.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_525c0a681746e',
				'label' => 'Number of Guest Reviews to show',
				'name' => '_eco_guest_reviews_count',
				'type' => 'number',
				'instructions' => 'Sets the maximum number of guest reviews to show on the homepage.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'front_page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_our-cuisine-menus',
		'title' => 'Our Cuisine: Menus',
		'fields' => array (
			array (
				'key' => 'field_523ef0be6a2d2',
				'label' => 'Main',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5252e655435ce',
				'label' => 'Main Menu Title',
				'name' => '_eco_main_menu_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_523ef0ee2580b',
				'label' => 'Main Menu Banner',
				'name' => '_eco_main_menu_banner',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_523ef19982a34',
				'label' => 'Main Menu - Sunday',
				'name' => '_eco_main_menu_sunday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_523ef1be82a35',
				'label' => 'Main Menu - Monday',
				'name' => '_eco_main_menu_monday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_523ef1ec4ae2f',
				'label' => 'Main Menu - Tuesday',
				'name' => '_eco_main_menu_tuesday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_523ef1f94ae30',
				'label' => 'Main Menu - Wednesday',
				'name' => '_eco_main_menu_wednesday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_523ef2044ae31',
				'label' => 'Main Menu - Thursday',
				'name' => '_eco_main_menu_thursday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_523ef2164ae32',
				'label' => 'Main Menu - Friday',
				'name' => '_eco_main_menu_friday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_523ef2204ae33',
				'label' => 'Main Menu - Saturday',
				'name' => '_eco_main_menu_saturday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_523ef0c86a2d3',
				'label' => 'Vegetarian',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5252e669435cf',
				'label' => 'Vegetarian Menu Title',
				'name' => '_eco_vegetarian_menu_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_523ef1172580c',
				'label' => 'Vegetarian Menu Banner',
				'name' => '_eco_vegetarian_menu_banner',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_523ef24b72561',
				'label' => 'Vegetarian Menu - Sunday',
				'name' => '_eco_vegetarian_menu_sunday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_523efd272ce0e',
				'label' => 'Vegetarian Menu - Monday',
				'name' => '_eco_vegetarian_menu_monday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5241aedd3f2e2',
				'label' => 'Vegetarian Menu - Tuesday',
				'name' => '_eco_vegetarian_menu_tuesday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5241aeee3f2e3',
				'label' => 'Vegetarian Menu - Wednesday',
				'name' => '_eco_vegetarian_menu_wednesday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5241aef93f2e4',
				'label' => 'Vegetarian Menu - Thursday',
				'name' => '_eco_vegetarian_menu_thursday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5241af043f2e5',
				'label' => 'Vegetarian Menu - Friday',
				'name' => '_eco_vegetarian_menu_friday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5241af0d3f2e6',
				'label' => 'Vegetarian Menu - Saturday',
				'name' => '_eco_vegetarian_menu_saturday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_523ef0cf6a2d4',
				'label' => 'Kids',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5252e679435d0',
				'label' => 'Kids Menu Title',
				'name' => '_eco_kids_menu_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_523ef1282580d',
				'label' => 'Kids Menu Banner',
				'name' => '_eco_kids_menu_banner',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_523efd3a2ce0f',
				'label' => 'Kids Menu - Sunday',
				'name' => '_eco_kids_menu_sunday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_523efd522ce10',
				'label' => 'Kids Menu - Monday',
				'name' => '_eco_kids_menu_monday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5241af183f2e7',
				'label' => 'Kids Menu - Tuesday',
				'name' => '_eco_kids_menu_tuesday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5241af223f2e8',
				'label' => 'Kids Menu - Wednesday',
				'name' => '_eco_kids_menu_wednesday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5241af303f2e9',
				'label' => 'Kids Menu - Thursday',
				'name' => '_eco_kids_menu_thursday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5241af393f2ea',
				'label' => 'Kids Menu - Friday',
				'name' => '_eco_kids_menu_friday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_5241af413f2eb',
				'label' => 'Kids Menu - Saturday',
				'name' => '_eco_kids_menu_saturday',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'no',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-cuisine.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
	register_field_group(array (
		'id' => 'acf_page-banner',
		'title' => 'Page Banner',
		'fields' => array (
			array (
				'key' => 'field_52197d7bb4278',
				'label' => 'Page Banner',
				'name' => '_eco_page_banner',
				'type' => 'image',
				'instructions' => 'Upload an image to be used as the banner at the top of the page. Ideal size: 1280px by 250px (optional)',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 1,
				),
				array (
					'param' => 'page_type',
					'operator' => '!=',
					'value' => 'front_page',
					'order_no' => 1,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'gallery',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 3,
	));
}
